CREATE TABLE link (
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     long_link varchar(100) NOT NULL

);



-- insert into URL (long_url) values ('http://kozey.info/qui-eligendi-ipsa-consequatur-eligendi-nulla-maxime-est-consequatur.html'),
--                                  ('https://green.com/sit-suscipit-voluptatibus-libero-assumenda-id-quis-ut.html'),
--                                  ('http://harris.com/'),
--                                  ('https://bednar.org/quae-voluptas-repellendus-pariatur-qui-vel.html'),
--                                  ('http://robel.com/sint-sit-modi-necessitatibus.html'),
--                                  ('http://mccullough.com/necessitatibus-quam-aut-sunt-aut-omnis-sit-incidunt-eaque'),
--                                  ('https://homenick.com/architecto-aut-pariatur-explicabo.html'),
--                                  ('http://www.becker.com/'),
--                                  ('http://ondricka.com/nobis-et-dolores-est-sapiente-sit-libero'),
--                                  ('http://shields.info/');

create table person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       person_name varchar(100) NOT NULL
);

-- insert into person (id, person_name) values ('1', 'ivan'),
--                                      ('2', 'pavel'),
--                                      ('3' ,'nikolay'),
--                                      ('4', 'oleg'),
--                                      ('5', 'dmitriy'),
--                                      ('6', 'alexey');
